In [2]:
import numpy as np

# Numpy Exercise Solution
###### Solutions by Jacob Caggese

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [8]:
np.random.randint(10,25,25)

array([18, 22, 13, 23, 16, 13, 10, 15, 21, 19, 10, 13, 13, 15, 17, 20, 11,
       12, 17, 22, 23, 12, 20, 10, 18])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [7]:
numArray = np.arange(1, 50, 2)
len(numArray)

25

#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [10]:
np.linspace(4, 7, 27)

array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [14]:
np.random.random((5,4)).round(2)

array([[0.49, 0.23, 0.25, 0.84],
       [0.13, 0.67, 0.8 , 0.92],
       [0.02, 0.47, 0.15, 0.12],
       [0.7 , 0.57, 0.17, 0.28],
       [0.58, 0.33, 0.44, 0.33]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [15]:
np.random.randint(5, 15, (5,5))

array([[ 5,  9, 11, 11, 14],
       [ 9,  6, 13, 13,  9],
       [ 9, 10,  6, 13, 13],
       [11, 12,  5, 12,  8],
       [ 5, 10, 12, 13, 11]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [21]:
np.zeros(np.random.randint(20),dtype='int32')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [28]:
np.ones((np.random.randint(1, 10),np.random.randint(1, 10)), dtype='float32')


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype

In [3]:
mtx = np.matrix(
    [[9, 25, 50, 34, 45],
    [3, 34, 34, 65, 2],
    [5, 7, 3, 76, 3],
    [7, 8, 6, 54, 6],
    [23, 12, 8, 5, 6]], dtype='int')
print(mtx)
print(f"Shape: {mtx.shape}\tDtype: {mtx.dtype}\tType: {type(mtx)}")


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  6]]
Shape: (5, 5)	Dtype: int32	Type: <class 'numpy.matrix'>


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [44]:
size = mtx.shape
mtx[int(size[0]/2), int(size[1]/2)]


3

#### 10. Print the all the elements of 3rd row of the matrix

In [45]:
mtx[2]


matrix([[ 5,  7,  3, 76,  3]])

#### 11. Print the all the elements of 4th columns of the matrix

In [51]:
mtx[:,3]


matrix([[34],
        [65],
        [76],
        [54],
        [ 5]])

#### 12. Print the 4 corner pixels of the matrix

In [53]:
print(f"{mtx[0,0]},{mtx[0,size[1]-1]},{mtx[size[0]-1,0]},{mtx[size[0]-1,size[1]-1]}")

9,45,23,6


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below

In [79]:
m1 = mtx[0:2,2:4]
m2 = mtx[3:, 0:2]
m3 = mtx[2:,2:]

print(m1,m2,m3,sep='\n')

[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  6]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [71]:
print(m1.flatten(),m2.flatten(),m3.flatten(),sep='\n')

[[50 34 34 65]]
[[ 7  8 23 12]]
[[ 3 76  3  6 54  6  8  5  6]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [87]:
print(np.concatenate((m1, m2)))
print(np.concatenate((m1, m2), axis=1))


[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]
[[50 34  7  8]
 [34 65 23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [89]:
# Solution
print(f"Addition:\n{m1 + m2}\nSubtraction:\n{m1 - m2}\nDivision:\n{m1 / m2}\n Multiplication:\n{m1 * m2}")

Addition:
[[57 42]
 [57 77]]
Subtraction:
[[43 26]
 [11 53]]
Division:
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]
 Multiplication:
[[350 272]
 [782 780]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [92]:
m1 + m3[1:,:2]


array([[56, 88],
       [42, 70]])

#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [106]:
m4 = np.concatenate((np.matrix(m1.mean(0)), m1))
m4

matrix([[42. , 49.5],
        [50. , 34. ],
        [34. , 65. ]])

#### 19. Perform the matrix multiplication between m3 and m4

In [109]:
m3 * m4



matrix([[4028. , 2927.5],
        [3156. , 2523. ],
        [ 790. ,  956. ]])

#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [112]:
print(f"Means:\n{mtx.mean(1)}\nVariance:\n{mtx.var(1)}\nStandard Deviation:\n{mtx.std(1)}")

Means:
[[32.6]
 [27.6]
 [18.8]
 [16.2]
 [10.8]]
Variance:
[[214.64]
 [548.24]
 [820.16]
 [357.76]
 [ 42.96]]
Standard Deviation:
[[14.65059726]
 [23.41452541]
 [28.63843571]
 [18.91454467]
 [ 6.55438784]]


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)

In [31]:
# Don't understand the question (How to calculate the values)
# strike = run / ball * 100
runs_scored = np.array([
    ['MSD',54,60,10,65],
    ['Kholi',102,2,78,32],
    ['Rohit',3,110,1,92],
    ['Rahul',56,6,12,42],
    ['Dhawan',12,8,22,11]
])

balls_faced = np.array([
    ['MSD',50,42,22,78],
    ['Kholi',95,8,65,43],
    ['Rohit',9,100,7,101],
    ['Rahul',27,3,11,31],
    ['Dhawan',24,20,36,27]

])

strike = runs_scored[:,1:].astype('int32') / balls_faced[:,1:].astype('int32') * 100
sr = strike.mean(axis=1).reshape(5,1)
averages = np.concatenate([balls_faced[:,0].reshape(5,1), sr], axis=1)

ind = sr.argsort(axis=0) #ascending

print(averages[ind,:][::-1])

[[['Rahul' '162.99554686651462']]

 [['MSD' '94.91125541125541']]

 [['Kholi' '81.69675642594859']]

 [['Rohit' '62.17703913248468']]

 [['Dhawan' '47.96296296296296']]]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [36]:
marks = np.array([65,84,47,56,89,98,48,77,80,39])
passed, failed = 0, 0
for mark in marks:
    if mark < 50:
        failed += 1
    else:
        passed += 1
passPercentage = passed / len(marks) * 100
print(f"Passed: {passed}\tFailed: {failed}")

#NumPy method
# pass_std= np.where(marks>50)
# pass_marks=marks[pass_std]
# fail_std= np.where(marks<50)
# fail_marks=marks[fail_std]
# print(len(fail_marks))

Passed: 7	Failed: 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [37]:
curvedMarks = []
passPostCurve, failPostCurve = 0, 0

for mark in marks:
    if mark >= 95:
        curvedMarks.append(100)
        passPostCurve += 1
    elif mark > 80:
        curvedMarks.append(mark + 5)
        passPostCurve += 1
    elif mark >= 45 and mark <= 49:
        curvedMarks.append(mark + 5)
        passPostCurve += 1
    else:
        curvedMarks.append(mark)
        if (mark < 45):
            failPostCurve += 1
        else:
            passPostCurve += 1

curvePassPercentage = passPostCurve / len(curvedMarks) * 100
print(f"{curvedMarks}\nIncrease in pass percentage: {passPercentage}%->{curvePassPercentage}% (+{curvePassPercentage - passPercentage}%)")

#NumPy method
# new_marks = marks.copy()
# mercy_marks = np.where((new_marks>=45)&(new_marks<=49))
# new_marks[mercy_marks]=new_marks[mercy_marks] + 5
# bonus_marks = np.where((new_marks>80)&(new_marks<95))
# new_marks[bonus_marks]=new_marks[bonus_marks] + 5
# new_marks1 = np.where(new_marks>95)
# new_marks[new_marks1] = 100
# print("\n actual marks: ", marks)
# print("\n new Marks of students: ", new_marks)
# actual_pass = (len(marks[np.where(marks>=50)])/len(marks))/100
# new_mark_out= (len(new_marks[np.where(new_marks>=50)])/len(new_marks))/100
# inc_percent = new_mark_out-actual_pass
# print(inc_percent,"%")


[65, 89, 52, 56, 94, 100, 53, 77, 80, 39]
Increase in pass percentage: 70.0%->90.0% (+20.0%)


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [140]:
# Im not sure what this is actually asking either
# May have misinterpreted this
import time
start = time.process_time()
x = list(range(1, 60000))
y = x.copy()

for i in range(59999):
    for j in range(59999):
        z = (x[i] ** 2 + 8) / y[j]
stop = time.process_time()
print(f"Python list: {stop - start}ms")

start = time.process_time()
x = np.array(range(1, 60000))
y = x.copy()
for i in range(59999):
    for j in range(59999):
        z = (x[i] ** 2 + 8) / y[j]
stop = time.process_time()
print(f"Numpy array: {stop - start}ms")

Python list: 708.359375ms
Numpy array: 664.59375ms


The above values should be in seconds, not ms. The numpy arrays ended up being over 40 seconds faster, undoubtedly due to optimizations from numpy